### ISSUE TITLE
Reading ship_traffic parquet files from a requester pays bucket

### ISSUE THREAD

**Issue by rsignell-usgs** [pyviz-topics/examples#138] opened 2021-02-19 13:19 UTC
I love the [ship_traffic demo](https://github.com/pyviz-topics/examples/blob/master/ship_traffic/ship_traffic.ipynb), and I'd like to customize and deploy my own panel app based on this example.

I would like to read the parquet datasets directly from S3 instead of [downloading the zip file](
https://github.com/pyviz-topics/examples/blob/master/ship_traffic/anaconda-project.yml#L52), and I have them in a requester pays bucket at: 
```python
vessels_file = 's3://esip-qhub/uscg/ship_traffic/AIS_2020_01_vessels.parq'
cache_file = 's3://esip-qhub/uscg/ship_traffic/AIS_2020_01_broadcast.parq'
```
I can read the vessels file with 
```python
df = dd.read_parquet(vessels_file, storage_options={'requester_pays':True, 'profile':'esip-qhub'})
```
but reading the cache file 
```python
gdf = dd.read_parquet(cache_file, storage_options={'requester_pays':True, 'profile':'esip-qhub'})
```
gives:
```python-traceback
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 2: invalid start byte
```
If I try to use the code in the notebook:
```python
gdf = sp.io.read_parquet_dask(cache_file)
```
I get:
```python-traceback
/home/conda/store/d05c9ede5b971baf68a3777b3053fe561bc2f06dd4b6433f0f277e17dbf5129b-pangeo/lib/python3.8/site-packages/pyarrow/compat.py:24: FutureWarning: pyarrow.compat has been deprecated and will be removed in a future release
  warnings.warn("pyarrow.compat has been deprecated and will be removed in a "
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-24-ea30c97c89a2> in <module>
----> 1 gdf = sp.io.read_parquet_dask(cache_file)

/home/conda/store/d05c9ede5b971baf68a3777b3053fe561bc2f06dd4b6433f0f277e17dbf5129b-pangeo/lib/python3.8/site-packages/spatialpandas/io/parquet.py in read_parquet_dask(path, columns, filesystem, load_divisions, geometry, bounds, categories)
    228 
    229     # Perform read parquet
--> 230     result = _perform_read_parquet_dask(
    231         path, columns, filesystem,
    232         load_divisions=load_divisions, geometry=geometry, bounds=bounds,

/home/conda/store/d05c9ede5b971baf68a3777b3053fe561bc2f06dd4b6433f0f277e17dbf5129b-pangeo/lib/python3.8/site-packages/spatialpandas/io/parquet.py in _perform_read_parquet_dask(paths, columns, filesystem, load_divisions, geometry, bounds, categories)
    319 
    320     # Import geometry columns in meta, not needed for pyarrow >= 0.16
--> 321     metadata = _load_parquet_pandas_metadata(paths[0], filesystem=filesystem)
    322     geom_cols = _get_geometry_columns(metadata)
    323     if geom_cols:

/home/conda/store/d05c9ede5b971baf68a3777b3053fe561bc2f06dd4b6433f0f277e17dbf5129b-pangeo/lib/python3.8/site-packages/spatialpandas/io/parquet.py in _load_parquet_pandas_metadata(path, filesystem)
     45     filesystem = validate_coerce_filesystem(path, filesystem)
     46     if not filesystem.exists(path):
---> 47         raise ValueError("Path not found: " + path)
     48 
     49     if filesystem.isdir(path):

ValueError: Path not found: s3://esip-qhub/uscg/ship_traffic/AIS_2020_01_broadcast.parq
```
which makes me spatialpandas is using pyarrow insead of fastparquet, and apparently doesn't have fsspec under the hood?

I also tried to use fsspec explicitly:
```python
with fsspec.open(cache_file,requester_pays=True, profile='esip-qhub' ) as f:
    gdf = sp.io.read_parquet_dask(f)
```
and got back:
```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-29-7b6428120741> in <module>
      1 with fsspec.open(cache_file,requester_pays=True, profile='esip-qhub' ) as f:
----> 2     gdf = sp.io.read_parquet_dask(f)

/home/conda/store/d05c9ede5b971baf68a3777b3053fe561bc2f06dd4b6433f0f277e17dbf5129b-pangeo/lib/python3.8/site-packages/spatialpandas/io/parquet.py in read_parquet_dask(path, columns, filesystem, load_divisions, geometry, bounds, categories)
    217         path = list(path)
    218         if not path:
--> 219             raise ValueError('Empty path specification')
    220 
    221     # Infer filesystem

ValueError: Empty path specification
```

@martindurant, I bet you know how I can read the parquet dataset: `cache_file = s3://esip-qhub/uscg/ship_traffic/AIS_2020_01_broadcast.parq` from a requester pays bucket into dask dataframe, am I right?

**Comment by martindurant** [comment] 2021-02-19 14:12
The `_metadata` file appears to be poorly constructed - the row groups' metadata does not have  path references to the constituent data files. I don't know exactly what spatial does, but maybe it assumes the file paths in some different way.

You can open the dataset with

```
df = dd.read_parquet(
    's3://esip-qhub/uscg/ship_traffic/AIS_2020_01_broadcast.parq/part*', 
    storage_options={'requester_pays': True}
)
```
(works with fastparquet, get `TypeError: data type 'point[float32]' not understood` with pyarrow - all on my local env versions)

**Comment by martindurant** [comment] 2021-02-19 14:36
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 2: invalid start byte`

cc @rjzamora - I believe this is a genuine bug at https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet/fastparquet.py#L442 - if the min/max is bytes, we cannot assume that it should be interpreted as string.

**Comment by rjzamora** [comment] 2021-02-19 15:09
>cc @rjzamora - I believe this is a genuine bug at https://github.com/dask/dask/blob/master/dask/dataframe/io/parquet/fastparquet.py#L442 - if the min/max is bytes, we cannot assume that it should be interpreted as string.

I will try to investigate this later.  Right now we are only interpreting the bytes as a string if the pandas type is not labeled as bytes.  In CI, the most common case is that the string interpretation is correct, so this may not be a trivial fix.  Do you have any suggestions to improve the logic around byte interpretation?

**Comment by rsignell-usgs** [comment] 2021-02-19 15:11
@martindurant, indeed, that works!    I guess I do need to read this with spatialpandas though, because the `geometry ` column doesn't look too good:
![2021-02-19_9-48-58](https://user-images.githubusercontent.com/1872600/108520506-c1fb4f00-7298-11eb-9771-a73b32323f82.png)

Do you know how to make spatialpandas read from s3, or is this a question for @jbednar or @brl0?

I tried this:
```
import spatialpandas as sp
sp.io.read_parquet('s3://esip-qhub/uscg/ship_traffic/AIS_2020_01_broadcast.parq/part*')
```
which gives: 
```
ValueError: Path not found: s3://esip-qhub/uscg/ship_traffic/AIS_2020_01_broadcast.parq/part*
```
So it appears it doesn't understand s3 endpoints.   

Is there a workaround with fsspec I could use to get spatialpandas to read this data from s3? 

I would know how to do it if were a single file, but will multiple parts, I'm not sure.

**Comment by martindurant** [comment] 2021-02-19 15:13
Sorry, I don't know what spatialpandas assumes/requires

**Comment by brl0** [comment] 2021-02-19 15:27
@rsignell-usgs,
For multipart parquet files, you should probably use the spatialpandas read_parquet_dask function.  Then if you want to consolidate the partitions into one dataframe you can call the `.compute()` method.

Also, you may need to pass the fsspec filesystem to the spatialpandas read_parquet_dask function.
Something like:
```python
import spatialpandas as sp
from fsspec.core import get_fs_token_paths

fs, fs_token, paths = get_fs_token_paths(path, storage_options=storage_options)
ddf = sp.io.read_parquet_dask(path, filesystem=fs)
df = ddf.compute()
```

**Comment by rsignell-usgs** [comment] 2021-02-19 15:35
@brl0, thanks so much.  I think there is something I don't understand though:
```python
import spatialpandas as sp
from fsspec.core import get_fs_token_paths
cache_file = 's3://esip-qhub/uscg/ship_traffic/AIS_2020_01_broadcast.parq/part*'
@blfs, fs_token, paths = get_fs_token_paths(cache_file, 
                                         storage_options={'requester_pays': True})
ddf = sp.io.read_parquet_dask(cache_file, filesystem=fs)
df = ddf.compute()
```
throws a similar error:
```python-traceback
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-67-8b99ee9ab391> in <module>
      5 fs, fs_token, paths = get_fs_token_paths(cache_file, 
      6                                          storage_options={'requester_pays': True})
----> 7 ddf = sp.io.read_parquet_dask(cache_file, filesystem=fs)
      8 df = ddf.compute()

/home/conda/store/d05c9ede5b971baf68a3777b3053fe561bc2f06dd4b6433f0f277e17dbf5129b-pangeo/lib/python3.8/site-packages/spatialpandas/io/parquet.py in read_parquet_dask(path, columns, filesystem, load_divisions, geometry, bounds, categories)
    228 
    229     # Perform read parquet
--> 230     result = _perform_read_parquet_dask(
    231         path, columns, filesystem,
    232         load_divisions=load_divisions, geometry=geometry, bounds=bounds,

/home/conda/store/d05c9ede5b971baf68a3777b3053fe561bc2f06dd4b6433f0f277e17dbf5129b-pangeo/lib/python3.8/site-packages/spatialpandas/io/parquet.py in _perform_read_parquet_dask(paths, columns, filesystem, load_divisions, geometry, bounds, categories)
    319 
    320     # Import geometry columns in meta, not needed for pyarrow >= 0.16
--> 321     metadata = _load_parquet_pandas_metadata(paths[0], filesystem=filesystem)
    322     geom_cols = _get_geometry_columns(metadata)
    323     if geom_cols:

/home/conda/store/d05c9ede5b971baf68a3777b3053fe561bc2f06dd4b6433f0f277e17dbf5129b-pangeo/lib/python3.8/site-packages/spatialpandas/io/parquet.py in _load_parquet_pandas_metadata(path, filesystem)
     45     filesystem = validate_coerce_filesystem(path, filesystem)
     46     if not filesystem.exists(path):
---> 47         raise ValueError("Path not found: " + path)
     48 
     49     if filesystem.isdir(path):

ValueError: Path not found: s3://esip-qhub/uscg/ship_traffic/AIS_2020_01_broadcast.parq/part.0.parquet
```

**Comment by brl0** [comment] 2021-02-19 16:01
@rsignell-usgs,
Try `cache_file = 's3://esip-qhub/uscg/ship_traffic/AIS_2020_01_broadcast.parq` without the glob.

If that does not work, you might be able to do something like this:
```python
import pandas as pd
from fsspec.core import get_fs_token_paths
from spatialpandas.io import read_parquet

cache_file = 's3://esip-qhub/uscg/ship_traffic/AIS_2020_01_broadcast.parq
fs, fs_token, paths = get_fs_token_paths(cache_file, 
                                         storage_options={'requester_pays': True})
dfs = [read_parquet(f"s3://{_}", filesystem=fs) for _ in fs.ls(cache_file)]
df = pd.concat(dfs)
```

**Comment by martindurant** [comment] 2021-02-19 16:04
Slight modification here
```
fs = fsspec.filesystem("s3", storage_options={'requester_pays': True})
dfs = [read_parquet(_, filesystem=fs) for _ in fs.glob(cache_file + "/part*")]
df = pd.concat(dfs)
```
but note that this is **not** dask/lazy.

**Comment by rsignell-usgs** [comment] 2021-02-19 16:24
Indeed, if I read just a few partitions it works:
```
import spatialpandas as sp
fs = fsspec.filesystem('s3', requester_pays=True)
dfs = [sp.io.read_parquet(_, filesystem=fs) for _ in fs.glob(f'{cache_file}/part.0*')]
df = pd.concat(dfs)  
```
![2021-02-19_11-20-06](https://user-images.githubusercontent.com/1872600/108531459-b4e45d00-72a4-11eb-83c6-1589fcb47749.png)
but if I try to load the whole dataset, it blows out the notebook memory on the JupyterHub I'm using.   

Is there a way to wrap or convert the Dask Dataframe into spatialpandas?    Seems like the info is there but as binary:
![2021-02-19_9-48-58](https://user-images.githubusercontent.com/1872600/108531714-00970680-72a5-11eb-84c5-b1c195e90bfa.png)

**Comment by brl0** [comment] 2021-02-19 16:40
I would have expected `read_parquet_dask` to have worked, and that it did not is probably a bug.  I think the problem likely occurred when the files were written.  I think I have encountered this issue in the past, but have honestly not yet taken the time to open an issue in the holoviz/spatialpandas repo.

Anyway, using delayed you might be able to 'daskify' the process.

```python
import dask.dataframe as dd
from dask import delayed
from spatialpandas.io import read_parquet

read_parquet = delayed(read_parquet)

fs = fsspec.filesystem('s3', requester_pays=True)
dfs = [read_parquet(_, filesystem=fs) for _ in fs.glob(f'{cache_file}/part*')]
df = dd.from_delayed(dfs)
```

**Comment by rsignell-usgs** [comment] 2021-02-19 19:03
@brl0 , that works great!  Thanks!
So I should raise an issue on spatialpandas to request using fsspec on the backend, just like dask dataframe, is that right?

**Comment by brl0** [comment] 2021-02-19 19:41
Let me first say I don't really know much about the workings of parquet files and pyarrow, so I am just guessing here.

I think there was a problem that potentially corrupted the metadata of the parquet files when they were written which causes the `ValueError: Path not found` issue.  We circumvented that issue by reading each parquet file individually, which then avoided the need to read the corrupt metadata.

I believe the fix that may be needed would address the circumstances that cause the metadata to be written incorrectly.
Anything you could provide that would lead to reproducible scenarios would probably be most helpful.  

Anyway, I really am just throwing out some thoughts out here that are not well grounded in knowledge of how pyarrow and parquet files actually work.  

Finally, I should mention that I don't think the work around provided above is well suited to working on a cluster.  If you are using a cluster, using something like `client.map` over the files would probably be better.

```python
from functools import partial

import dask.dataframe as dd
from dask import delayed
from dask.distributed import get_client
from fsspec.core import get_fs_token_paths
from spatialpandas.io import read_parquet

cache_file = 's3://esip-qhub/uscg/ship_traffic/AIS_2020_01_broadcast.parq'
fs, fs_token, paths = get_fs_token_paths(cache_file, 
                                         storage_options={'requester_pays': True})

read_parquet_delayed = partial(delayed(read_parquet), filesystem=fs)

client = get_client()
files = list(fs.glob(f'{cache_file}/part*'))
futures = client.map(read_parquet_delayed, files)

dfs = client.gather(futures)
ddf = dd.from_delayed(dfs)
```

**Comment by jbednar** [comment] 2021-02-19 21:51
Nice to see all the discussion here! The Parquet file that anaconda-project.yml downloads was created using the code in ship_traffic.ipynb, and will be recreated if you run the notebook without the .parq directory present but with the original CSV files present. So if there are bugs in how the parquet file was created, it should be easy enough to replicate that process.

It's not clear how much we really gain here by using SpatialParquet to save the file, and I was planning to make a version without doing that to see. The hilbert tree spatial indexing isn't buying us as much speedup as I would have expected.  So some of the complexity here may not be necessary in practice. It's hard to find the time to dedicate to figuring that out, though!

**Comment by rsignell-usgs** [comment] 2021-02-21 16:35
@jbednar , perhaps you could throw me a bone here.  I download a sample CSV and can process it, but I'm not sure how you are suggesting these lines should be changed:
```
            print('Reading CSV files')
            gdf = dd.read_csv(csvs, usecols=dfcols, assume_missing=True)
            gdf = gdf.map_partitions(convert_partition, meta=example).persist()

            print('Writing parquet file')
            gdf = gdf.pack_partitions_to_parquet(cache_file, npartitions=64).persist()
```
I tried to use `engine=fastparquet` as an arg to `pack_partitions_to_parquet`, but I guess that's not an option.

**Comment by jbednar** [comment] 2021-02-21 18:22
I'm not suggesting to change any lines; if the notebook is run as-is in the environment provided, it should recreate the .parq file already if there isn't one.

**Comment by ppwadhwa** [comment] 2021-05-03 15:33
It looks like there is no immediate action to take here.  Closing for now, but feel free to re-open if there is a specific request.

**Closed by ppwadhwa** 2021-05-03 15:33 UTC
